services:
  - type: web
    name: facial-recognition
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    python:
      version: 3.10.11